"""initial migration

Revision ID: 968787b0ca4d
Revises: 330f22702c47
Create Date: 2019-04-17 13:18:09.409487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968787b0ca4d'
down_revision = '330f22702c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
